### ISSUE TITLE
To sqlite?

### ISSUE THREAD

**Issue by AfzalivE** [cbick/gtfs_SQL_importer#1]
Hi,
I was wondering how much change would it require from this code to import it to SQLite instead of SQL. (I don't know much about DBMS structures)

Thanks

**Comment by cbick** [comment]
There are probably differences in syntax/types, but it's been a while since I've used SQLite (note that SQLite is a dbms, whereas SQL is a language). Your best bet is to just try it and fix what breaks. I would definitely use the -nocopy option when running the python script however.

**Comment by AfzalivE** [comment]
hmm, I'll check it out. Thanks.
