### ISSUE TITLE
Error in use of agency_id

### ISSUE THREAD

**Issue by jcwong86** [cbick/gtfs_SQL_importer#5]
Able to set up tables but fails to populate when it hits errors with agency_id:
ERROR:  column "﻿agency_id" of relation "gtfs_agency" does not exist

Tried with different feeds with and without an agency_id and some work while others dont. SEPTA has no agency_id and worked, MTA Maryland had a 1 and worked. Arlington had a 1 and failed. TriMet had nothing and failed.

**Comment by cbick** [comment]
Can you link me to the GTFS file you're importing?

**Comment by cbick** [comment]
Ok I'm trying this on the latest TriMet and I notice that a couple of the column names in my code are out of date. I'll fix those. But there are still errors in the data -- for example, in stops.txt the column name should be direction_id and not direction.

**Comment by cbick** [comment]
oh sorry that's trips.txt. destination is an unofficial feature that's been proposed in gtfs-changes. I'll fix that too :)

**Comment by cbick** [comment]
Should be fixed now.
